### ISSUE TITLE
Use HTTPS !!!

### ISSUE THREAD

**Issue by frntn** [hyperhq/hyper-installer#16]
**Nobody should `curl | sh` on untrusted url !**

https://github.com/hyperhq/hyper-installer/blob/master/README.md#install-hypercontainer

One could use a modified copy of your installer on a different server
He could silently install a rootkit before installing hypercontainer.
The enduser won't see any issue.

_But its whole multi-tenant infrastructure is now compromised...._

**Comment by frntn** [comment]
It seems `hypercontainer.io` and `hyper.sh` share the same certificate : 

```
$ echo | openssl s_client -showcerts -connect hypercontainer.io:443 2>/dev/null | grep ^subject=
subject=/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.hyper.sh
```

A longterm fix can take some time (new cert, new setup, test, deploy, etc....)
But this **CRITICAL ISSUE** requires a shortterm fix.

I would suggest using github's raw link to installer

```
https://raw.githubusercontent.com/hyperhq/hyper-installer/master/hyper-bootstrap.sh
```

**Comment by gnanet** [comment]
Using letsencrypt without auto-renew is not a good solution. Currently `hypercontainer.io` and `docs.hypercontainer.io` have expired certs
