### ISSUE TITLE
Confused in file location specification.

### ISSUE THREAD

**Issue by imdjh** [hyperhq/hyper-installer#3]
Where the **./install.sh** script copy binary(hyperd, hyper) to? 
Why you make a link from /usr/local/ to /usr? What's the point?

As a script(against package), I think its better to install systemd cfg to /etc/systemd.
If you want to migrate this as a script in packaging. Please also get us notice(in comments of course).

**Comment by gnawux** [comment]
@imdjh 

Thank you for your reviewing and contribution. The scripts are temp installation methods for pre-1.0 releases. And we will prepare native packages later. We'd like to learn your more ideas.

**Comment by imdjh** [comment]
@gnawux 
Thanks for your response. I have using the ``Getting started'' part from your website, founding that installation script has the same content as in this repo.
I'd like to PR for some code quality improvements with you, hope it helps.
